<?php

/*
 * Created by Roman Senchuk.
 * at 22.12.17 14:10
 */

require __DIR__.'/vendor/autoload.php';
require 'Asserter.php';

/**
 * Class AsserterTest
 * @author Roman Senchuk frspm.roman@gmail.com
 */
class AsserterTest extends \PHPUnit\Framework\TestCase
{

    public const EXPRESSION = '200+12*((1/8)+1)-19';

    /**
     * @var Asserter
     */
    protected $assert;

    protected function setUp()
    {
        $this->assert = new Asserter();
        parent::setUp(); // TODO: Change the autogenerated stub
    }


    public function testParseNumber()
    {
        $f = '235Єва';
        $result = $this->assert->parseNumber($f);
        self::assertEquals(235, $result);
    }

    public function testParseFactor()
    {
        $factor = 12 * 5;
        $result = $this->assert->parseFactor($factor);

        self::assertEquals(60, $result);
    }
}
